#!/usr/bin/env bash

STARTDIR=`pwd`
SERVICES="../counting-service/"
mkdir -p pkg/zips
cd counting-service/


OSES='windows solaris'
ARCHS='amd64 386'
OSARCH='!darwin/386'
gox -os="${OSES}" -arch="${ARCHS}" -osarch="${OSARCH}" "${SERVICES}"


OSES='darwin'
ARCHS='amd64 arm64'
OSARCH='!darwin/386'
gox -os="${OSES}" -arch="${ARCHS}" -osarch="${OSARCH}" ${SERVICES}


OSES='linux freebsd'
ARCHS='arm arm64 amd64 386'
gox -os="${OSES}" -arch="${ARCHS}" "${SERVICES}"

mv counting-service* ../pkg/
cd ../pkg/
FILES=`ls -pd * | grep -v /`
echo $FILES
echo "Checksumming and compressing builds..."
for FILE in ${FILES}
do
  echo "  ${FILE}..."
  zip zips/${FILE}.zip ${FILE}
  shasum --algorithm 256 zips/${FILE}.zip >> zips/SHA256SUMS.txt
done

cd ${STARTDIR}


cd dashboard-service/
SERVICES="../dashboard-service/"

OSES='windows solaris'
ARCHS='amd64 386'
OSARCH='!darwin/386'
gox -os="${OSES}" -arch="${ARCHS}" -osarch="${OSARCH}" "${SERVICES}"

OSES='darwin'
ARCHS='amd64 arm64'
OSARCH='!darwin/386'
gox -os="${OSES}" -arch="${ARCHS}" -osarch="${OSARCH}" ${SERVICES}

OSES='linux freebsd'
ARCHS='arm arm64 amd64 386'
gox -os="${OSES}" -arch="${ARCHS}" "${SERVICES}"

mv dashboard-service* ../pkg/
cd ../pkg/
FILES=`ls -pd * | grep -v /`
echo $FILES
echo "Checksumming and compressing builds..."
for FILE in ${FILES}
do
  echo "  ${FILE}..."
  zip zips/${FILE}.zip ${FILE}
  shasum --algorithm 256 zips/${FILE}.zip >> zips/SHA256SUMS.txt
done