apiVersion: v1
kind: Pod
metadata:
  name: counting
  annotations:
    consul.hashicorp.com/connect-inject: "true"
spec:
  containers:
  - name: counting
    image: hashicorp/counting-service:0.0.2
    ports:
    - containerPort: 9001
      name: http